In [ ]:
import pandas as pd
from google.cloud import storage

def filtrar_paises(data, context):
    # Obtener información del archivo CSV desde el evento de Cloud Storage
    file_data = data

    # Obtener la ruta del archivo en el bucket de Cloud Storage
    bucket_name = file_data['stage_esperanzadevida']
    file_name = file_data['che_coded.csv']
    file_path = f"gs://{file_name}/{bucket_name}"
    
    # Leer el archivo CSV en un DataFrame
    data = pd.read_csv(file_path)
    
    # Eliminar columnas
    columnas_a_eliminar = ['PUBLISHSTATE', 'REGION', 'Display Value', 'Low', 'High', 'StdErr', 'StdDev', 'Comments']
    data = data.drop(columnas_a_eliminar, axis=1)
    
    # Lista de países a mantener
    paises_lista = ['DEU', 'AUS', 'CAN', 'ESP', 'USA', 'ITA', 'JPN', 'GBR', 'RUS', 'SWE',
                   'ALB', 'ARG', 'BRA', 'COL', 'VNM', 'PHL', 'IND', 'IDN', 'MEX', 'PER',
                    'ZAF', 'THA', 'AFG', 'BGD', 'EGY', 'ETH', 'IRQ', 'IRN', 'KEN', 'MAR']
    
    # Filtrar el DataFrame por los países de la lista
    data_filtrado = data[data['COUNTRY'].isin(paises_lista)]
    
    # Especificar la ruta y el nombre de archivo para guardar el DataFrame filtrado
    output_bucket_name = 'limpiezatotal'
    output_file_name = 'che_code_etl.csv'
    output_file_path = f"gs://{output_bucket_name}/{output_file_name}"
    
    # Guardar el DataFrame filtrado en un archivo CSV en el bucket de Cloud Storage de destino
    data_filtrado.to_csv(output_file_path, index=False)
    
    # Retornar una respuesta, por ejemplo, un mensaje de éxito
    return 'Datos filtrados y cargados exitosamente en el bucket de destino.'

In [12]:
data

           GHO  YEAR WORLDBANKINCOMEGROUP COUNTRY  Numeric
0     WHS4_117  2000               WB_UMI     ALB     96.0
11    WHS4_117  2000               WB_UMI     BRA     94.0
17    WHS4_117  2000               WB_UMI     COL     78.0
21    WHS4_117  2000                WB_HI     DEU     84.0
24    WHS4_117  2000               WB_LMI     EGY     98.0
...        ...   ...                  ...     ...      ...
3655  WHS4_117  2021                WB_HI     SWE     98.0
3661  WHS4_117  2021               WB_UMI     THA     97.0
3674  WHS4_117  2021                WB_HI     USA     91.0
3678  WHS4_117  2021               WB_LMI     VNM     83.0
3682  WHS4_117  2021               WB_UMI     ZAF     86.0

[575 rows x 5 columns]

In [ ]:
import pandas as pd
from google.cloud import storage

def filtrar_paises(data, context):
    # Obtener información del archivo CSV desde el evento de Cloud Storage
    file_data = data

    # Obtener la ruta del archivo en el bucket de Cloud Storage
    bucket_name = file_data['bucket']
    file_name = file_data['name']
    file_path = f"gs://{bucket_name}/{file_name}"
    
    # Leer el archivo CSV en un DataFrame
    data = pd.read_csv(file_path)
    
    # Eliminar columnas
    columnas_a_eliminar = ['PUBLISHSTATE', 'REGION', 'Display Value', 'Low', 'High', 'StdErr', 'StdDev', 'Comments']
    data = data.drop(columnas_a_eliminar, axis=1)
    
    # Lista de países a mantener
    paises_lista = ['DEU', 'AUS', 'CAN', 'ESP', 'USA', 'ITA', 'JPN', 'GBR', 'RUS', 'SWE',
                   'ALB', 'ARG', 'BRA', 'COL', 'VNM', 'PHL', 'IND', 'IDN', 'MEX', 'PER',
                    'ZAF', 'THA', 'AFG', 'BGD', 'EGY', 'ETH', 'IRQ', 'IRN', 'KEN', 'MAR']
    
    # Filtrar el DataFrame por los países de la lista
    data_filtrado = data[data['COUNTRY'].isin(paises_lista)]
    
    # Especificar la ruta y el nombre de archivo para guardar el DataFrame filtrado
    output_bucket_name = 'nombre_bucket_destino'
    output_file_name = 'nombre_archivo_destino.csv'
    output_file_path = f"gs://{output_bucket_name}/{output_file_name}"
    
    # Guardar el DataFrame filtrado en un archivo CSV en el bucket de Cloud Storage de destino
    data_filtrado.to_csv(output_file_path, index=False)
    
    # Retornar una respuesta, por ejemplo, un mensaje de éxito
    return 'Datos filtrados y cargados exitosamente en el bucket de destino.'

In [3]:
import pandas as pd
import numpy as np

In [51]:
data=pd.read_csv('data_original_oms/hepatitis_coded.csv')

In [15]:
import pandas as pd
import numpy as np
data=pd.read_csv('data_original_oms/che_coded.csv')
# Eliminar columnas
columnas_a_eliminar = ['PUBLISHSTATE','REGION','Display Value','Low','High','StdErr','StdDev','Comments']
data = data.drop(columnas_a_eliminar, axis=1)

# Lista de países a mantener
paises_lista = ['DEU', 'AUS', 'CAN', 'ESP', 'USA', 'ITA', 'JPN', 'GBR', 'RUS', 'SWE',
                   'ALB', 'ARG', 'BRA', 'COL', 'VNM', 'PHL', 'IND', 'IDN', 'MEX', 'PER',
                    'ZAF', 'THA', 'AFG', 'BGD', 'EGY', 'ETH', 'IRQ', 'IRN', 'KEN', 'MAR']

# Filtrar el DataFrame por los países de la lista
data = data[data['COUNTRY'].isin(paises_lista)]

In [16]:
data

                         GHO  YEAR COUNTRY  Numeric
0     GHED_CHE_pc_US_SHA2011  2002     AFG    17.01
1     GHED_CHE_pc_US_SHA2011  2003     AFG    17.81
2     GHED_CHE_pc_US_SHA2011  2004     AFG    21.43
3     GHED_CHE_pc_US_SHA2011  2005     AFG    25.11
4     GHED_CHE_pc_US_SHA2011  2006     AFG    28.92
...                      ...   ...     ...      ...
3856  GHED_CHE_pc_US_SHA2011  2016     VNM   124.74
3857  GHED_CHE_pc_US_SHA2011  2017     VNM   141.01
3858  GHED_CHE_pc_US_SHA2011  2018     VNM   164.24
3859  GHED_CHE_pc_US_SHA2011  2019     VNM   173.65
3860  GHED_CHE_pc_US_SHA2011  2020     VNM   166.23

[623 rows x 4 columns]

In [57]:
data.to_csv('hepatitis.csv',index=False)

In [ ]:
# Calcular el porcentaje de valores nulos por columna
porcentaje_nulos = (data.isnull().mean() * 100).round(2)

# Imprimir el resultado
print(porcentaje_nulos)

In [ ]:
data_hepatitis=pd.read_csv('data_original_oms/hepatitis_coded.csv')

In [ ]:
data_hepatitis

In [ ]:
# Eliminar columnas
columnas_a_eliminar = [['ValueType', 'ParentLocationCode', 'ParentLocation', 'Location type',
                         'SpatialDimValueCode', 'Location', 'Period type', 'Period', 'IsLatestYear', 'Dim1 type', 'Dim1',
                           'Dim1ValueCode', 'Dim2 type', 'Dim2', 'Dim2ValueCode', 'Dim3 type', 'Dim3', 'Dim3ValueCode',
                             'DataSourceDimValueCode', 'DataSource', 'FactValueNumericPrefix', 'FactValueNumeric', 'FactValueUoM',
                               'FactValueNumericLowPrefix', 'FactValueNumericLow', 'FactValueNumericHighPrefix', 'FactValueNumericHigh',
                                 'Value', 'FactValueTranslationID', 'FactComments', 'Language', 'DateModified']]
data_hepatitis = data_hepatitis.drop(columnas_a_eliminar, axis=1)

In [ ]:
# Obtener lista de columnas
columnas = data_hepatitis.columns.tolist()
# Imprimir lista de columnas
print(columnas)

In [ ]:
data_hepatitis

In [ ]:
data_hepatitis.info